### ISSUE TITLE
Need to publish/receive data as byte[] instead of String.

### ISSUE THREAD

**Issue by vipulpurohit** [iGenius-Srl/android-mqtt-service#3]
Hello
Thanks for this amazing wrapper over MQTT.

I need to transmit image data in byte[] format over using MQTT. Your library does only support for data in text format.
I can convert the byte[] in Base64 and then decode it at receivers end, but it's require additional computation and sometime I'm getting weird size limit exception too. As per my knowledge MQTT itself transport data in byte[] format.

I modified you library and made some changes to make it work with byte[] data but for that I've almost destroyed you architecture. So I guess you are the best person to make this change.
Can you please add support for byte[] format data publish/receive.

Thanks

**Comment by gotev** [comment]
Thank you @vipulpurohit 
The library was made to work with strings on purpose, as its main usage is in [crystal.io](https://play.google.com/store/apps/details?id=net.igenius.crystal) Android App and we needed like that. I know MQTT itself is based on byte arrays and to support it, many things of the current architecture has to be revisited or changed. One main factor is that you cannot pass large byte data in Android intents, so you have to store it somewhere and then retrieve it when needed. This adds the need for a local storage. Everything gets simpler if we consider supporting only small byte payloads, in which case the architecture can remain untouched. I'm curious about how you made the implementation and what architecture you used in your own fork. If you want to share your design decisions here, you're welcome.

**Comment by gotev** [comment]
@vipulpurohit the library now supports binary payloads. Keep in mind that they have to be < 1MB otherwise you may have overflow errors. MQTT is intended for small payloads. Just update your dependency to 1.5
