### ISSUE TITLE
Username/Password Authentification [Question]

### ISSUE THREAD

**Issue by alexgtn** [iGenius-Srl/android-mqtt-service#5]
Simple question.

A bit confused :)
For what purpose does the client provide the username and password?
Does the client sign up at first login?
Who provides the username and password?
Or should I randomly generate 2 strings as the username and password for each client?

**Comment by krombel** [comment]
The username and the password will be used to connect to the MQTT Broker as the broker might not allow anonymous connections.
If you want to connect without providing credentials just pass `null` for both values
